"""
Generate the reference index and command list from the filesystem.

Both `.claude/REFERENCE/INDEX.md` and `.claude/commands/help.md` are lists of
files that exist on disk, and both were hand-maintained until 2026-07-30. Both
had drifted badly: INDEX was missing 22 of 54 reference docs — including
VOICE-PROFILE.md (the most-linked doc in the repo) and all seven
WRITING-VOICE-AND-STYLE-P* parts — while /help advertised commands that were
never written.

A hand-maintained list of files is a generated artifact wearing a disguise, so
this generates it. The generated region lives inside an AUTO fence (reusing
tools/video_projects/status_doc.AutoZone, the repo's marker machinery); prose
outside the fence is yours and is never touched.

CLI:
    python -m tools.docs_index --check     # exit 1 if regeneration would change
    python -m tools.docs_index --write
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

from tools.logging_config import get_logger, setup_logging
from tools.video_projects.status_doc import AutoZone

logger = get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
REFERENCE_DIR = REPO_ROOT / ".claude" / "REFERENCE"
COMMANDS_DIR = REPO_ROOT / ".claude" / "commands"
INDEX_PATH = REFERENCE_DIR / "INDEX.md"
HELP_PATH = COMMANDS_DIR / "help.md"

INDEX_ZONE = AutoZone("reference-index", "generated by tools/docs_index.py — do not hand-edit")
HELP_ZONE = AutoZone("command-list", "generated by tools/docs_index.py — do not hand-edit")

# Files that are not reference docs in their own right.
INDEX_SKIP = {"INDEX.md"}


def _frontmatter_description(text: str) -> str:
    """`description:` from YAML frontmatter, if the file has any."""
    if not text.startswith("---"):
        return ""
    end = text.find("\n---", 3)
    if end == -1:
        return ""
    match = re.search(r"^description:\s*(.+)$", text[:end], re.MULTILINE)
    return match.group(1).strip().strip("\"'") if match else ""


def _summary(path: Path) -> str:
    """One-line summary: frontmatter description, else the first bold/plain line
    after the H1, else empty. Never raises on unreadable files."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        logger.warning("Could not read %s: %s", path.name, exc)
        return ""

    desc = _frontmatter_description(text)
    if desc:
        return desc

    lines = text.splitlines()
    seen_h1 = False
    for line in lines[:40]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("# "):
            seen_h1 = True
            continue
        if not seen_h1:
            continue
        if stripped.startswith(("---", "<!--", "|", ">", "#")):
            continue
        # Collapse markdown emphasis and trailing punctuation noise.
        clean = re.sub(r"[*_`]", "", stripped)
        clean = re.sub(r"\s+", " ", clean).strip()
        if clean:
            return clean[:150]
    return ""


def _title(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return path.stem
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else path.stem


def build_index_body() -> str:
    rows: List[Tuple[str, str, str]] = []
    for path in sorted(REFERENCE_DIR.glob("*.md")):
        if path.name in INDEX_SKIP:
            continue
        rows.append((path.name, _title(path), _summary(path)))

    lines = [
        f"*{len(rows)} reference documents. Regenerate with "
        "`python -m tools.docs_index --write`.*",
        "",
        "| Document | What it covers |",
        "|---|---|",
    ]
    for name, title, summary in rows:
        detail = summary or title
        detail = detail.replace("|", "\\|")
        lines.append(f"| [{name}]({name}) | {detail} |")
    return "\n".join(lines)


def build_help_body() -> str:
    rows: List[Tuple[str, str]] = []
    for path in sorted(COMMANDS_DIR.glob("*.md")):
        if path.name == "help.md":
            continue
        rows.append((path.stem, _summary(path)))

    lines = [
        f"*{len(rows)} commands, generated from `.claude/commands/`. Regenerate with "
        "`python -m tools.docs_index --write`.*",
        "",
        "| Command | Purpose |",
        "|---|---|",
    ]
    for stem, summary in rows:
        lines.append(f"| `/{stem}` | {summary.replace('|', chr(92) + '|')} |")
    return "\n".join(lines)


def command_drift() -> Tuple[List[str], List[str]]:
    """(cited-but-missing, real-but-unmentioned) for help.md's curated section.

    The generated table below the fence always lists every command, but the
    hand-written phase menu above it is where people actually read.

    The consolidation/deprecation list is skipped deliberately. It names retired
    commands on purpose ("`/sources` -> `/research --sources`"), so scanning it
    reports every redirect as a ghost — 9 false positives on first run. It did
    catch one real error though: /preflight was listed as archived while the
    command existed, which is the inverse mistake and worth still catching.
    """
    if not HELP_PATH.exists():
        return [], []
    text = HELP_PATH.read_text(encoding="utf-8", errors="replace")
    curated = text.split("<!-- AUTO:command-list", 1)[0]
    curated = curated.split("<!-- /AUTO:command-list -->")[-1]
    # Drop the "consolidation:" redirect table — everything after it documents
    # history, not the live menu.
    curated = re.split(r"^\*\*\d{4}-\d{2}-\d{2} consolidation:", curated, flags=re.MULTILINE)[0]

    real = {p.stem for p in COMMANDS_DIR.glob("*.md")}
    cited = set(re.findall(r"`/([a-z0-9][a-z0-9-]*)", curated))
    return sorted(cited - real), sorted(real - cited - {"help"})


def _split_frontmatter(text: str) -> Tuple[str, str]:
    """Split a leading YAML frontmatter block off the body.

    Command files carry `---\\ndescription: ...\\nmodel: ...\\n---`, and YAML
    frontmatter is only frontmatter when it is the very first thing in the file.
    Writing an AUTO fence at the top therefore breaks it — on the first run of
    this tool it made /help's description read as the HTML comment. Returns
    ('', text) for files with no frontmatter, so INDEX.md is unaffected.
    """
    if not text.startswith("---"):
        return "", text
    end = text.find("\n---", 3)
    if end == -1:
        return "", text
    cut = end + len("\n---")
    if cut < len(text) and text[cut] == "\n":
        cut += 1
    return text[:cut], text[cut:]


def _apply(path: Path, zone: AutoZone, body: str, write: bool) -> bool:
    """Returns True if the file content would change (or did)."""
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    frontmatter, rest = _split_frontmatter(original)
    updated = frontmatter + zone.write(rest, body)
    if updated == original:
        return False
    if write:
        path.write_text(updated, encoding="utf-8")
        # relative_to raises for anything outside the repo (e.g. a tmp_path in
        # tests), and a log line must never be the thing that fails a write.
        try:
            shown = path.relative_to(REPO_ROOT)
        except ValueError:
            shown = path
        logger.info("Rewrote %s", shown)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate INDEX.md and help.md from the filesystem.",
        epilog=("Examples:\n"
                "  python -m tools.docs_index --check\n"
                "  python -m tools.docs_index --write\n"),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--write", action="store_true", help="rewrite the files in place")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if regeneration would change anything")
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--verbose", "-v", action="store_true")
    group.add_argument("--quiet", "-q", action="store_true")
    args = ap.parse_args()
    setup_logging(args.verbose, args.quiet)

    if not args.write and not args.check:
        ap.error("pass --write or --check")

    changed = [
        _apply(INDEX_PATH, INDEX_ZONE, build_index_body(), args.write),
        _apply(HELP_PATH, HELP_ZONE, build_help_body(), args.write),
    ]

    ghosts, unmentioned = command_drift()
    if ghosts:
        print(f"docs_index: help.md's curated menu cites {len(ghosts)} command(s) that "
              f"do not exist: {', '.join('/' + g for g in ghosts)}")
    if unmentioned:
        print(f"docs_index: {len(unmentioned)} real command(s) missing from the curated "
              f"menu: {', '.join('/' + u for u in unmentioned)}")

    if args.check and (any(changed) or ghosts):
        if any(changed):
            print("docs_index: INDEX.md / help.md are stale — "
                  "run `python -m tools.docs_index --write`")
        return 1
    print("docs_index: " + ("updated" if (args.write and any(changed)) else "up to date"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
