$content = @"
When you search through history books you will find many anecdotes on the role that alcohol and other addictive substances played in shaping societies throughout human history. The Pharaohs of ancient Egypt paid their farm laborers in bread and beer. Greek wine was one of the most prized commodities of the ancient world, so when the Carthaginians sold their low-quality wine abroad they falsely labeled it as Greek wine. The British notoriously forced access and control over the 19th century Chinese economy by illegally selling opium to its people.

But no historic relationship between a society and an addictive substance is as fascinating, sinister, and barely talked about as the relationship between Russia and vodka. There is nothing special about vodka. It has no taste, no flavor, no smell—it is just ethyl alcohol simply produced from wheat or rye. And these simple, not too special facts of vodka is exactly what made it so special. Its simplicity allowed it to be produced and consumed en masse by simple peasants throughout Eastern Europe beginning in the 8th century. Any peasant could make it and any peasant could sell it—until the 1480s.

Until then the lands we know as Russia were a set of small independent principalities and kingdoms, until Ivan the Third became the ruler of the Duchy of Moscow and by conquest united the principalities into one Russian Kingdom of which he became the Tsar. Ivan established a centralized government with a centralized autocratic rule controlled by the king, and as he built his state he noticed the popularity of that cheap intoxicating spirit amongst his peasants and had an idea.

He banned the production and sale of alcohol by peasants and declared the production and sale of alcohol a royal privilege. All alcohol was now the property of the Russian crown and could only be produced by and bought from the Russian crown. This was a guaranteed source of revenue for the Russian royal family—a monopoly on a cheap product that everyone wanted and which could be very cheaply produced en masse.

Throughout the centuries the Tsars opened vodka plant after vodka plant, pumping out cheap alcohol while filling their own pockets—a system that was so profitable that when Catherine the Great rewarded lesser nobles for their service she did not give them land but vodka production and selling grants to cash in on this lucrative monopoly. A system that lasted for almost four hundred and twenty-eight years.

And as much as this may sound like just a mere little interesting historic anecdote on a long-gone mercantile economic system, there is far more to it than that—something sinister, the reverberations of which still echo throughout Russian society to this day.

Alcohol is a poison harmful to the soul and body. Therefore it is a great sin to drink alcohol and to offer it to others, and it is even a greater sin to produce and sell this poison. This phrase is from Tolstoy.

When Tsar Nicholas II had to rescind powers to an elected body in 1905, one of the first things the Russian liberals and social democrats who were newly elected into a position of power wished to do was to combat the massive alcoholism problems of Russia. The first step was to ask the famous and revered novelist to write a warning label to be printed on every single bottle of vodka. The Tsar, who owned the entire alcohol industry, refused.

Because the system the Tsars established over the course of four hundred years was not only a source of revenue—by controlling the entire market they also determined the price, and consequently kept the population drunk on a constant mass supply of cheap and widely available vodka. A peasant who wastes his money on vodka is too drunk to think of his situation and how he got into it. Too drunk to organize any protest against his circumstances. So drunk he beats his kids into being drunks like him. And so drunk he beats his wife into submission.

In the end, that peasant is a peasant in service of ensuring the security of the regime that keeps him drunk. The Tsars of Russia established a profitable system of state-subsidized alcoholism which not only ensured them personal wealth but the security of their regime. They were in essence drug dealers—or at least reliant on the same addiction-fed market that a drug dealer would rely on.

Alcohol addiction is a horrible disease. It increases blood pressure, inflamed and swollen blood vessels, kidney, pancreas, and liver failure that leads to an excess of fat cells creating deformed abdomens. But far from just individual effects, alcohol is also part of a vicious social circle of misery. Nobody wakes up one day and decides to become an addict. Addiction is preconditioned on misery and despair. It appears where there is despair and hopelessness, and perversely increases that hopelessness.

The alcoholic not only becomes more hopeless and miserable themselves but will contribute to the misery and hopelessness of those around him. Perplexingly, addiction on the massive social scale creates social strife and misery while simultaneously robbing those affected by it of the means to do something about it. This is why the drug trade comes with violent social decline—the disaffection of communities—because it uses misery as an economic commodity.

It is because of this, and largely forgotten today, that the Russian Communist Party was a prohibitionist party that advocated for the banning of liquor. In early Soviet propaganda you will find this reflected, as well as in old Soviet movies in which the revolutionaries smash liquor bottles as if they were chains that had constrained them. Leninism was strictly prohibitionist and declared alcohol to be a vice by which the bourgeoisie subjugated and controlled the proletariat.

Consequently, after the Bolshevik takeover, the Tsar's vodka plants were all shut down and closed for a while. When Stalin seized power, he reopened the vodka plants, started filling bottles again, and distributed them cheaply amongst the public. Stalin pretty much rebuilt the old Tsarist system of subsidized alcoholism that the revolutionaries had tried to dismantle. He just renamed it to "the people's vodka" in a very cynical move. The Russian people already had a "people's vodka" for 400 years.

This series of events is commented on by George Orwell in his famous book Animal Farm—an often overlooked scene where the animals in their revolution destroy all the alcohol they found in the house of the farmer Jones, except for Napoleon who steals himself away with some liquor.

And the Tsar's system which was reestablished by Stalin remained in place throughout the remaining 60 years of Soviet history. Its effects were most strongly felt starting in the 1970s and throughout the 1980s during the Soviet Union's increasing economic decline. In those days there was not much to work for. There was not much to celebrate. There was a lost war still being fought in Afghanistan. And there was not much for the state to sell. But there was always money to be made when socialism fails by selling bottles of cheap vodka to a miserable public.

The recent HBO series Chernobyl did an excellent job at hinting to its audience how, by the late 1980s, Russian society had a deep-seated and systematic alcoholism problem. The Stolichnaya vodka bottles you see in the series are also somewhat famous because you could not close them anymore once you took the cap off. They were made that way because in production the assumption was that the average Russian opening a vodka bottle would finish it in one sitting—therefore closing the bottle was not necessary.

By the late 1980s the alcoholism problem reached such an extent that Gorbachev in desperation enacted a prohibition of liquor. This resulted in the mass appearance of illegal vodka plants throughout the country. It was therefore abandoned.

Today, almost 30 years after the collapse of the Soviet Union, the problems remain. The system of state-subsidized alcoholism no longer exists. The vodka plants though were privatized and are owned by oligarchs who still sell the vodka at cheap prices. No measures were taken by the Russian government to stem the banal systemic alcoholism and excessive alcohol consumption of the Russian public. The ramifications of such are of course felt in crime rates, productivity, and social decline and misery.

Russia will eventually not get around having to confront a legacy of 400 years of alcoholism. And this is more than just a history lesson, let alone restricted to Russia. Think of the current opiate crisis in the United States—how the current response to social misery is to dish out pills to help people stomach through the days and lives. How fully legal dependency on addictive substances was created in the United States at a profit that uses social and individual misery as a market commodity. And more to the point, how it is largely ignored and not a topic of contention.

Drug-riddled and miserable communities often find themselves within such a state because it is the misery and hopelessness that creates the perfect market conditions for addictive substances, which consequently increase the misery and violence while robbing communities of the ability to rid themselves thereof. The entirety of our understanding of addiction and how it plays into society through the ills it creates is largely flawed and dominated far too much by a judgmental standard that reduces the problem to individuals to be punished rather than social ills in need of solutions.

If you are interested in this topic and want to know more, I recommend to you to read "Drink: A Cultural History of Alcohol" by Ian Gately.
"@

$content | Out-File -FilePath 'D:\History vs Hype\transcripts\Kraut\How Vodka ruined Russia.txt' -Encoding UTF8
Write-Host "Vodka transcript corrected!"
