"""
Generate LIBRARY-INDEX.md from the source library on disk.

`library/` is the persistent source library — 1,600+ PDFs behind every video's
primary-source work, gitignored binaries with a tracked index. That index was
hand-maintained and had drifted badly by 2026-07-31: it claimed "416 books, 21
organized (5%)" against a real 1,148 filed and 594 stashed, and documented a
naming convention (`Author - Title (Year).pdf`) that not one file uses.

A hand-maintained list of files that exist on disk is a generated artifact
wearing a disguise — the same conclusion `tools/docs_index.py` reached for
`.claude/REFERENCE/INDEX.md`. This generates it, inside an AutoZone fence so any
prose written outside is preserved.

The catalogue is the point: the library's own README says "open LIBRARY-INDEX.md
and press Ctrl+F", so every title is listed rather than summarised.

CLI:
    python -m tools.library_index --check     # exit 1 if regeneration would change
    python -m tools.library_index --write
"""

import argparse
import re
import sys
from collections import Counter
from pathlib import Path
from typing import List, NamedTuple

from tools.logging_config import get_logger, setup_logging
from tools.video_projects.status_doc import AutoZone

logger = get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
LIBRARY_DIR = REPO_ROOT / "library"
INDEX_PATH = LIBRARY_DIR / "LIBRARY-INDEX.md"

ZONE = AutoZone("library-index", "generated by tools/library_index.py — do not hand-edit")

BOOK_SUFFIXES = {".pdf", ".epub", ".mobi", ".azw3", ".djvu"}

# A resolvable author: letters, apostrophes and hyphens only. Anything else
# means the filename did not parse, and citation_check cannot reach the book.
CONFORMING = re.compile(r"[A-Za-zÀ-ÿ'’-]{2,30}")


class Book(NamedTuple):
    title: str
    author: str
    year: str
    publisher: str
    filename: str


def parse_name(stem: str) -> Book:
    """Split the live convention `TitleWords-Author-Year-Publisher`.

    Note this is NOT the convention the old index documented. The files were
    renamed by `library/auto_rename_books.py` into this shape, and the doc was
    never updated — so the doc, not the files, was wrong.
    """
    parts = stem.split("-")
    if not parts:
        return Book(stem, "Unknown", "", "", stem)

    # Anchor on the year, not on field position. Hyphenated surnames are common
    # in this collection -- Maddy-Weitzman, Ndlovu-Gatsheni, Cold-Ravnkilde --
    # and taking parts[1] as the author truncated 65 of 1,151 books to their
    # first barrel, which also made them unresolvable by citation_check.
    # Search from index 1: the TITLE is sometimes itself a year -- `1491-Mann-
    # 2011-Libgen`, `1776-McCullough-2005-RandomHouse` -- and anchoring on parts[0]
    # left those with no year and flagged them as malformed.
    year_at = next((i for i, p in enumerate(parts) if i > 0 and re.fullmatch(r"\d{4}", p)), None)

    title = _spaced(parts[0])
    if year_at and year_at > 1:
        author = "-".join(parts[1:year_at])
        year = parts[year_at]
        publisher = _spaced("-".join(parts[year_at + 1:]))
    else:
        author = parts[1] if len(parts) > 1 else "Unknown"
        year = ""
        publisher = _spaced("-".join(parts[2:])) if len(parts) > 2 else ""
    return Book(title, author, year, publisher, stem)


def _spaced(camel: str) -> str:
    """`SomaliaSomalilandHistory` -> `Somalia Somaliland History`, so the
    catalogue is readable and Ctrl+F on a normal word works."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", camel).strip()


def collect(library=None) -> dict:
    """{topic: [Book]} for filed books, plus stash counts. Never raises."""
    base = Path(library) if library else LIBRARY_DIR
    topics: dict = {}
    by_topic = base / "by-topic"
    if by_topic.is_dir():
        for topic_dir in sorted(p for p in by_topic.iterdir() if p.is_dir()):
            books = [
                parse_name(f.stem)
                for f in sorted(topic_dir.rglob("*"))
                if f.is_file() and f.suffix.lower() in BOOK_SUFFIXES
            ]
            topics[topic_dir.name] = books
    stashes = {
        d.name: sum(1 for f in d.rglob("*") if f.is_file())
        for d in sorted(base.glob("_stash-*")) if d.is_dir()
    }
    return {"topics": topics, "stashes": stashes}


def build_body(data: dict) -> str:
    topics, stashes = data["topics"], data["stashes"]
    filed = sum(len(v) for v in topics.values())
    stashed = sum(stashes.values())

    lines: List[str] = [
        f"**{filed} books filed** across {len(topics)} topics · "
        f"**{stashed} unfiled** in stashes · regenerate with "
        "`python -m tools.library_index --write`",
        "",
        "Binaries are gitignored; this index is tracked, so the catalogue travels "
        "between machines even though the files do not.",
        "",
        "## File naming",
        "",
        "The live convention, produced by `auto_rename_books.py`:",
        "",
        "```",
        "TitleWords-Author-Year-Publisher.pdf",
        "SomaliaSomalilandHistory-Lewis-2008-IndianaUP.pdf",
        "```",
        "",
        "`tools/preflight/citation_check.py --library` resolves a citation to a file by "
        "the **Author** field, so that position is load-bearing — a book filed with the "
        "author in the wrong slot cannot be used to verify a quote.",
        "",
        "## Filed by topic",
        "",
        "| Topic | Books |",
        "|---|---|",
    ]
    for topic, books in topics.items():
        lines.append(f"| [{topic}](#{topic}) | {len(books)} |")
    if stashes:
        lines += ["", "## Unfiled", "", "| Stash | Files | Meaning |", "|---|---|---|"]
        meaning = {
            "_stash-duplicates": "same work already filed elsewhere",
            "_stash-needs-id": "author/title could not be parsed — needs a human",
            "_stash-offtopic": "outside the channel's subject range",
        }
        for name, count in stashes.items():
            lines.append(f"| `{name}` | {count} | {meaning.get(name, '—')} |")

    unresolvable = [(t, b) for t, books in topics.items() for b in books
                    if not CONFORMING.fullmatch(b.author) or not b.year]
    if unresolvable:
        lines += [
            "", "## Needs renaming", "",
            f"**{len(unresolvable)} of {filed}** do not follow the convention, so "
            "`citation_check --library` cannot resolve a citation to them — a quote from "
            "one of these can never be verified. Rename to "
            "`TitleWords-Author-Year-Publisher`.",
            "", "| File | Parsed author | Topic |", "|---|---|---|",
        ]
        for topic, b in sorted(unresolvable, key=lambda x: x[1].filename.casefold()):
            lines.append(f"| `{b.filename[:70]}` | {b.author or '—'} | {topic} |")

    for topic, books in topics.items():
        lines += ["", f"## {topic}", "", f"*{len(books)} books.*", "",
                  "| Title | Author | Year | Publisher |", "|---|---|---|---|"]
        for b in sorted(books, key=lambda x: (x.author.casefold(), x.title.casefold())):
            row = [b.title, b.author, b.year or "—", b.publisher or "—"]
            lines.append("| " + " | ".join(c.replace("|", "\\|") for c in row) + " |")
    return "\n".join(lines)


def apply(write: bool, library=None) -> bool:
    """Returns True if the index content would change (or did)."""
    path = (Path(library) / "LIBRARY-INDEX.md") if library else INDEX_PATH
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    updated = ZONE.write(original, build_body(collect(library)))
    if updated == original:
        return False
    if write:
        path.write_text(updated, encoding="utf-8")
        logger.info("Rewrote %s", path.name)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate library/LIBRARY-INDEX.md from the files on disk.",
        epilog=("Examples:\n"
                "  python -m tools.library_index --check\n"
                "  python -m tools.library_index --write\n"),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the index is stale")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--verbose", "-v", action="store_true")
    g.add_argument("--quiet", "-q", action="store_true")
    args = ap.parse_args()
    setup_logging(args.verbose, args.quiet)

    if not args.write and not args.check:
        ap.error("pass --write or --check")

    changed = apply(args.write)
    data = collect()
    filed = sum(len(v) for v in data["topics"].values())

    if args.check and changed:
        print(f"library_index: LIBRARY-INDEX.md is stale ({filed} books on disk) — "
              "run `python -m tools.library_index --write`")
        return 1
    print(f"library_index: {filed} books filed, "
          f"{sum(data['stashes'].values())} unfiled — "
          + ("updated" if (args.write and changed) else "up to date"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
